apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f /Users/greguska/githubprojects/esgf/esgf-docker/docker-compose-greguska.yml
      convert
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: slcs-nginx
  name: slcs-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: slcs-nginx
    spec:
      containers:
      - image: nginx
        name: slcs-nginx
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: slcs-static-web
        - mountPath: /etc/nginx/conf.d/default.conf
          name: slcs-nginx-claim1
      restartPolicy: Always
      volumes:
      - name: slcs-static-web
        persistentVolumeClaim:
          claimName: slcs-static-web
      - name: slcs-nginx-claim1
        persistentVolumeClaim:
          claimName: slcs-nginx-claim1
status: {}
