apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift -f /Users/greguska/githubprojects/esgf/esgf-docker/docker-compose-greguska.yml
      convert
    kompose.version: 1.7.0 (767ab4b)
  creationTimestamp: null
  labels:
    io.kompose.service: esgf-postgres
  name: esgf-postgres
spec:
  replicas: 1
  selector:
    io.kompose.service: esgf-postgres
  strategy:
    resources: {}
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: esgf-postgres
    spec:
      containers:
      - image: ' '
        name: postgres
        ports:
        - containerPort: 5432
        resources: {}
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: pg-data
      restartPolicy: Always
      volumes:
      - name: pg-data
        persistentVolumeClaim:
          claimName: pg-data
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - postgres
      from:
        kind: ImageStreamTag
        name: esgf-postgres:1.4
    type: ImageChange
status: {}
